import PrimeProvider from "./provider/PrimeProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "primereact/resources/themes/md-light-indigo/theme.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimeProvider>{children}</PrimeProvider>
      </body>
    </html>
  );
}
